# Python Course

## lecture 3 :session 2

### <ins>Python Math</ins>

### Built-in Math Functions

In [15]:
#The min() and max() functions can be used to find the lowest or highest value in an iterable:
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

5
25


In [17]:
#The abs() function returns the absolute (positive) value of the specified number:
x = abs(-7.25)

print(x)

7.25


In [21]:
# The pow(x, y) function returns the value of x to the power of y 
x = pow(4, 3)

print(x)

64


### <u>The Math Module</u>

Python has also a built-in module called math, which extends the list of mathematical functions.

To use it, you must import the math module

In [25]:
import math

In [27]:
# The math.sqrt() method for example, returns the square root of a number:
x = math.sqrt(64)

print(x)

8.0


In [31]:
#The math.ceil() method rounds a number upwards to its nearest integer, 
x = math.ceil(1.4)
#the math.floor() method rounds a number downwards to its nearest integer
y = math.floor(1.4)
print(x)
print(y)

2
1


In [33]:
#The math.pi constant, returns the value of PI (3.14...):
x = math.pi

print(x)

3.141592653589793


### <u>The NumPy Module</u>

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python.

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called **ndarray** , it provides a lot of supporting functions that make working with ndarray very easy.

In [5]:
#import 
import numpy as np

#### 1) Creating NumPy Arrays

In [44]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [46]:
np.array(my_list)

array([1, 2, 3])

In [48]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [50]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 ### 2) arange

In [7]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### 3) zeros

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4) ones

In [17]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5) linspace

In [22]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [24]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### note: 
 difference between arange and linspace : arange allow you to define the size of the step.linspace allow you to define the number of steps

### 6) rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [32]:
np.random.rand(3)

array([0.76598436, 0.91262334, 0.76254705])

In [34]:
np.random.rand(5, 5)

array([[0.72085312, 0.18368247, 0.10457645, 0.19830778, 0.19147121],
       [0.52145347, 0.60447286, 0.05534472, 0.76641258, 0.4271814 ],
       [0.66982202, 0.74796656, 0.44345063, 0.37882735, 0.66989452],
       [0.86794666, 0.84069639, 0.22557281, 0.24950165, 0.10413338],
       [0.96456103, 0.43294452, 0.31832076, 0.84662566, 0.20876507]])

### 7) randint
Return random integers from low (inclusive) to high (exclusive).

In [38]:
np.random.randint(1, 100)

55

In [42]:
ranarr=np.random.randint(1, 100, 10)
ranarr

array([50, 43,  7, 59, 66, 42, 10, 34, 17, 44])

### 8) max

In [45]:
ranarr.max()

66

### 10) argmax
return the index of max value

In [48]:
ranarr.argmax()

4

### 11) min

In [53]:
ranarr.min()

7

### 12) argmin
return the index of min

In [60]:
ranarr.argmin()

2

### 13) shape 

In [67]:
ranarr.shape

(10,)

### 14) Reshape
Returns an array containing the same data with a new shape.

In [71]:
arr = np.arange(25)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr.shape

(25,)

In [77]:
reshaped = arr.reshape(5, 5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
reshaped.shape

(5, 5)

In [81]:
reshaped.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
reshaped.reshape(25).shape

(25,)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [91]:
arr.reshape(1, 25).shape

(1, 25)

In [93]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [95]:
arr.reshape(25, 1).shape

(25, 1)

### 15) mean

In [117]:
arr.mean()

12.0

### 16) flatten() 
function is used to convert a multi-dimensional NumPy array into a one-dimensional array. It creates a new copy of the data so that original array stays unchanged. 

In [121]:
a = np.array([[5, 6], [7, 8]])
res = a.flatten()
print(res)

[5 6 7 8]


In [125]:
a = np.full([2, 2], 67, dtype = int) 
a

array([[67, 67],
       [67, 67]])

### <u>NumPy Indexing and Selection</u>

**1) Indexing a 1D array (Vectors)**

In [102]:
#Get a value at an index
arr[8]

8

In [104]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [106]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [108]:
arr[:5]

array([0, 1, 2, 3, 4])

In [110]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [112]:
arr[3:7]

array([3, 4, 5, 6])

In [114]:
arr[3:7:2]

array([3, 5])